name: Node.js Package

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build first
      - run: cd packages/experiment-gpr-multiple-first
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      # - run: npm test
      # Build second
      - run: cd ../experiment-gpr-multiple-second
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      # - run: npm test
      # Build third
      - run: cd ../experiment-gpr-multiple-third
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      # - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      # Publish first
      - run: cd packages/experiment-gpr-multiple-first
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # Publish second
      - run: cd ../experiment-gpr-multiple-second
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # Publish third
      - run: cd ../experiment-gpr-multiple-third
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}