name: Node.js Package

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: '**/package-lock.json'
      - run: cd packages/experiment-gpr-multiple-first && npm ci
      - run: cd packages/experiment-gpr-multiple-first && npm test
      - run: cd packages/experiment-gpr-multiple-second && npm ci
      - run: cd packages/experiment-gpr-multiple-second && npm test
      - run: cd packages/experiment-gpr-multiple-third && npm ci
      - run: cd packages/experiment-gpr-multiple-third && npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache-dependency-path: '**/package-lock.json'
          registry-url: https://npm.pkg.github.com/
      - run: cd packages/experiment-gpr-multiple-first && npm ci
      - run: cd packages/experiment-gpr-multiple-second && npm ci
      - run: cd packages/experiment-gpr-multiple-third && npm ci
      - run: |
          npm publish packages/experiment-gpr-multiple-first
          npm publish packages/experiment-gpr-multiple-second
          npm publish packages/experiment-gpr-multiple-third
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}